---
title: "Rproj"
date: "21/03/2025"
author: "-"
---

Créer un projet RStudio permet d´organiser tous vos scripts R et les fichiers (données, sorties...) relatifs à un même projet statistique. Un projet RStudio est un environnement isolé qui évite les conflits entre différents scripts et packages de projets statistiques distincts.

1.  Pour créer un projet RStudio, il suffit d´aller dans File \> New Project \> New Directory \> New Project \> (renseigner le nom de son projet, cliquer « git » et « renv » si besoin) \> Create Project

2.  RStudio va créer un fichier .Rproj à la racine du dossier du projet choisi, qui permet entre autres d´indiquer à R que vous travaillez dans ce dossier (working directory). En double-cliquant sur le Rproj, RStudio s'ouvre directement dans votre espace projet, et vous pouvez utiliser les chemins relatifs !

3.  En haut à droite de l'interface RStudio, vous pouvez naviguer entre vos différents projets.

4.  Pour la configuration du projet RStudio, il est conseillé de ne pas sauvegarder l´espace de travail (données en mémoire visibles dans votre environnement), ni de le recharger, pour des raisons de reproductibilité.